"""Canonical topic and type definitions for the math wiki."""

CANONICAL_TOPICS: frozenset[str] = frozenset({
    "algebra",
    "geometry",
    "calculus",
    "trigonometry",
    "combinatorics",
    "number_theory",
    "statistics",
    "probability",
    "differential_equations",
    "linear_algebra",
    "multivariable_calculus",
})

# Maps every known non-canonical slug → canonical topic.
# Unmapped slugs that aren't already canonical get soft-deleted by fix_topic_slugs.py.
TOPIC_MAP: dict[str, str] = {
    # algebra family
    "precalculus": "algebra",
    "sequences": "algebra",
    "sequences-and-series": "algebra",
    "series": "algebra",
    "complex-numbers": "algebra",
    "complex_numbers": "algebra",
    "complex_analysis": "algebra",
    "analysis": "algebra",
    "set theory": "algebra",
    "optimization": "algebra",
    "functions": "algebra",
    "vectors": "algebra",
    # calculus family
    "calculus-2": "calculus",
    "calculus-3": "calculus",
    "calculus-iii": "calculus",
    "integration": "calculus",
    "fourier analysis": "calculus",
    "fourier-analysis": "calculus",
    "fourier_analysis": "calculus",
    "fourier_series": "calculus",
    "Fourier Analysis": "calculus",
    "parametric equations": "calculus",
    "parametric-equations": "calculus",
    "numerical-methods": "calculus",
    # differential equations
    "differential equations": "differential_equations",
    "differential-equations": "differential_equations",
    "ordinary-differential-equations": "differential_equations",
    "ordinary_differential_equations": "differential_equations",
    "partial differential equations": "differential_equations",
    "partial-differential-equations": "differential_equations",
    "partial_differential_equations": "differential_equations",
    "laplace-transforms": "differential_equations",
    "laplace_transforms": "differential_equations",
    # number theory
    "number theory": "number_theory",
    "number-theory": "number_theory",
    # linear algebra
    "linear algebra": "linear_algebra",
    "linear-algebra": "linear_algebra",
    # multivariable calculus
    "multivariable-calculus": "multivariable_calculus",
    "3-dimensional space": "multivariable_calculus",
    "coordinate-systems": "multivariable_calculus",
    "vector-calculus": "multivariable_calculus",
    "vector_calculus": "multivariable_calculus",
    "vector-functions": "multivariable_calculus",
    # statistics family
    "nonparametric statistics": "statistics",
    "nonparametric_statistics": "statistics",
    "hypothesis_testing": "statistics",
    "hypothesis testing": "statistics",
    "descriptive statistics": "statistics",
    "descriptive_statistics": "statistics",
    "inferential statistics": "statistics",
    "inferential_statistics": "statistics",
    "bayesian statistics": "statistics",
    "bayesian_statistics": "statistics",
    # probability family
    "stochastic processes": "probability",
    "stochastic_processes": "probability",
    "random variables": "probability",
    "random_variables": "probability",
    # geometry family
    "analytic geometry": "geometry",
    "analytic-geometry": "geometry",
    "analytic_geometry": "geometry",
    "projective geometry": "geometry",
    "projective-geometry": "geometry",
    "projective_geometry": "geometry",
    "euclidean geometry": "geometry",
    "euclidean-geometry": "geometry",
    "euclidean_geometry": "geometry",
    "triangle-geometry": "geometry",
    "triangle_geometry": "geometry",
    "solid geometry": "geometry",
    "solid-geometry": "geometry",
    "solid_geometry": "geometry",
}

CANONICAL_TYPES: frozenset[str] = frozenset({
    "procedure",
    "concept",
    "theorem",
    "definition",
    "fact",
})

TYPE_MAP: dict[str, str] = {
    "application": "concept",
    "overview": "concept",
    "strategy": "concept",
    "principle": "concept",
    "property": "concept",
    "constraint": "concept",
    "convention": "concept",
    "warning": "concept",
    "reference": "concept",
    "problem": "concept",
    "worked_example": "procedure",
    "example": "procedure",
    "identity": "fact",
    "formula": "fact",
    "rule": "fact",
    "proof": "theorem",
    "derivation": "theorem",
    "result": "theorem",
}
