/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: ['selector', '[data-theme="dark"], .dark'],
  theme: {
    extend: {
      fontFamily: {
        sans:    ['"Be Vietnam Pro"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'system-ui', 'sans-serif'],
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        mono:    ['"JetBrains Mono"', '"Fira Code"', 'monospace'],
      },
      colors: {
        background:          'var(--background)',
        foreground:          'var(--foreground)',
        surface:             'var(--surface)',
        'surface-elevated':  'var(--surface-elevated)',
        border:              'var(--border)',
        'border-subtle':     'var(--border-subtle)',
        primary:             'var(--primary)',
        'primary-fg':        'var(--primary-fg)',
        'primary-subtle':    'var(--primary-subtle)',
        'primary-border':    'var(--primary-border)',
        accent:              'var(--accent)',
        'accent-fg':         'var(--accent-fg)',
        'accent-subtle':     'var(--accent-subtle)',
        'accent-border':     'var(--accent-border)',
        muted:               'var(--muted)',
        'muted-fg':          'var(--muted-fg)',
        dim:                 'var(--dim)',
        faint:               'var(--faint)',
        success:             'var(--success)',
        destructive:         'var(--destructive)',
        info:                'var(--info)',
        purple:              'var(--purple)',
        highlight:           'var(--highlight)',
        whatsapp:            '#25D366',
        'mastery-0':         'var(--mastery-0)',
        'mastery-0-bg':      'var(--mastery-0-bg)',
        'mastery-1':         'var(--mastery-1)',
        'mastery-1-bg':      'var(--mastery-1-bg)',
        'mastery-2':         'var(--mastery-2)',
        'mastery-2-bg':      'var(--mastery-2-bg)',
        'mastery-3':         'var(--mastery-3)',
        'mastery-3-bg':      'var(--mastery-3-bg)',
        'mastery-4':         'var(--mastery-4)',
        'mastery-4-bg':      'var(--mastery-4-bg)',
        'mastery-5':         'var(--mastery-5)',
        'mastery-5-bg':      'var(--mastery-5-bg)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
    },
  },
  plugins: [],
}
